spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3377/article_like?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rnrdj123
  kafka:
    kafka-server: localhost:9092
    consumer:
      group-id: article-service
      auto-offset-reset: earliest
